### ISSUE TITLE
MiniZinc.jl import problem on Windows

### ISSUE THREAD

**Issue by mhechthz** [jump-dev/MiniZinc.jl#18] opened 2022-12-01 15:35 UTC
I posted this recently but now it vanished.

If I import MiniZinc I get the error:

`ERROR: LoadError: InitError: Unsupported platform`

Importing a second time is no problem. so I have to do the following

```
print("import libs ...")
ENV["JULIA_LIBMINIZINC_DIR"] = "C:\\bin\\MiniZinc"
try
    import MiniZinc
catch
    println("catch ERROR: LoadError: InitError: Unsupported platform ...")
    import MiniZinc
end
const MOI=MiniZinc.MOI
print("import libs done ...")
```
So after this all works well. Where is the problem?

**Comment by odow** [comment] 2022-12-01 15:57
Your issue was here: https://github.com/jump-dev/MiniZinc.jl/issues/15

I fixed it in https://github.com/jump-dev/MiniZinc.jl/pull/17

A new version is available: https://github.com/jump-dev/MiniZinc.jl/releases/tag/v0.2.0

Please update your packages.

**Comment by odow** [comment] 2022-12-01 16:04
All-in-all, MiniZinc.jl is new and it is still a little rough. Please keep reporting bugs and feature requests :smile:

**Comment by mhechthz** [comment] 2022-12-01 16:46
So I did :-)

**Comment by odow** [comment] 2022-12-01 22:32
Closing as a duplicate of #15

**Closed by odow** 2022-12-01 22:32 UTC
